### ISSUE TITLE
No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by elisiano** [kris-nova/krex#16]
Hi, I was trying this but when the current context's user is authenticating with OIDC it errors out:

```bash
$ krex -v4
  _
 | |
 | | ___ __ _____  __
 | |/ / '__/ _ \ \/ /
 |   <| | |  __/>  <
 |_|\_\_|  \___/_/\_\

Kubernetes Resource Explorer

2018-07-04T20:36:20-04:00 [✖]  error during init: No Auth Provider found for name "oidc"
$
```

I tried using another context which uses basic auth and it works as expected.

PS: this is very neat and useful, thank you! Now I just need to remove the bell sound on my terminal otherwise it will drive me nuts 😃

**Comment by scottrigby** [comment]
See #20
