### ISSUE TITLE
Bug: Krex rings bell on every input

### ISSUE THREAD

**Issue by apeschel** [kris-nova/krex#28]
Running ZSH in iterm2, and Krex is ringing the bell on every input stroke. This does not seem intentional.

krex version 08c767b

**Comment by brkcmd** [comment]
I dug into this a bit yesterday and it looks like this is the related upstream issue: https://github.com/manifoldco/promptui/issues/49

AIUI the bell comes from `promptui` using [`chzyer/readline`](https://github.com/chzyer/readline) to draw on the terminal; `readline` handles every up/down keystroke internally as a request to [move through its own history](https://github.com/chzyer/readline/blob/f6d7a1f6fbf35bbf9beb80dc63c56a29dcfb759f/operation.go#L265-L278), which is empty, thus causing it to ring the bell.

I sat defeated by the herd of yaks at that point.

**Comment by kris-nova** [comment]
I want to re-write the prompt in C anyway - which would fix this

I'll start on that today
