### ISSUE TITLE
Right arrow key inconsistency

### ISSUE THREAD

**Issue by justinliew** [kris-nova/krex#35]
It feels like the right arrow key doesn't work consistently. When highlight is at the top, it goes to the end of the list (which seems like the correct behaviour) but when selection is in the middle of the list it does nothing.

**Comment by scottrigby** [comment]
The key behavior is partly from chzyer/readline and partly from manifoldco/promptui.

readline accepts a `Config` struct, containing a `Listener`:
>Any key press will pass to Listener
https://github.com/chzyer/readline/blob/master/readline.go#L28

readline standard shortcuts are here:
https://github.com/chzyer/readline/blob/master/doc/shortcut.md

promptui sets the Listener with specific cases for keys here:
https://github.com/manifoldco/promptui/blob/master/select.go#L129

(Looking through that, it's fun to note you can also use `h`, `j`, `k`, `l`)
